
services:
  webserver:
    build: ./webserver
    ports:
      - "5000:5000"
    networks:
      - trust_network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - trust_network

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - trust_network
    restart: unless-stopped

  ping-exporter:
    image: czerwonk/ping_exporter:latest
    container_name: ping-exporter
    ports:
      - "9427:9427"
    restart: unless-stopped
    cap_add:
      - NET_RAW
    volumes:
      - ./prometheus/ping_exporter.yml:/config/config.yml:ro
    networks:
      - trust_network

networks:
  trust_network:
    external: true
